In [1]:
import pandas as pd
import os

In [2]:
# Set the directory path where your CSV files are located
directory_path = r'F:\3.price data\FUTURES\BTCUSDT\excel'

# Get a list of all CSV files in the directory
csv_files = [file for file in os.listdir(directory_path) if file.endswith('.csv')]

# Initialize an empty list to store dataframes
dataframes = []

# Loop through each CSV file and read it into a dataframe, then append to the list
for csv_file in csv_files:
    csv_path = os.path.join(directory_path, csv_file)
    df = pd.read_csv(csv_path)
    dataframes.append(df)

# Concatenate all dataframes into a single dataframe
df = pd.concat(dataframes, ignore_index=True)

print("CSV files concatenated'")

CSV files concatenated'

In [4]:
df

                   open_time      open      high       low     close   volume
0        2020-01-01 00:00:00   7189.43   7190.52   7177.00   7182.44  246.092
1        2020-01-01 00:01:00   7182.43   7182.44   7178.75   7179.01   70.909
2        2020-01-01 00:02:00   7179.01   7179.01   7175.25   7177.93   99.420
3        2020-01-01 00:03:00   7177.77   7182.60   7177.00   7181.11   69.330
4        2020-01-01 00:04:00   7179.10   7179.10   7172.94   7175.25   97.368
...                      ...       ...       ...       ...       ...      ...
1871994  2023-07-31 23:55:00  29226.00  29226.10  29219.40  29220.00   89.605
1871995  2023-07-31 23:56:00  29220.00  29224.40  29219.90  29224.30   87.196
1871996  2023-07-31 23:57:00  29224.30  29224.40  29220.80  29220.80   27.859
1871997  2023-07-31 23:58:00  29220.90  29220.90  29220.80  29220.80   31.458
1871998  2023-07-31 23:59:00  29220.80  29220.90  29220.80  29220.80   20.112

[1871999 rows x 6 columns]

In [5]:
# Load your CSV file with the modified open_time and initial 6 columns
#df = pd.read_csv("concated.csv")

# Convert the 'open_time' column to a datetime index
df['open_time'] = pd.to_datetime(df['open_time'])
df.set_index('open_time', inplace=True)

# Resample the data to 5-minute intervals and aggregate using OHLCV (Open, High, Low, Close, Volume)
df = df.resample('5T').agg({'open': 'first', 
                                      'high': 'max', 
                                      'low': 'min', 
                                      'close': 'last', 
                                      'volume': 'sum'})

In [6]:
df

                         open      high       low     close   volume
open_time
2020-01-01 00:00:00   7189.43   7190.52   7172.94   7175.25  583.119
2020-01-01 00:05:00   7174.71   7186.69   7173.28   7186.69  163.860
2020-01-01 00:10:00   7186.83   7188.10   7175.70   7176.26  290.358
2020-01-01 00:15:00   7176.22   7179.41   7172.43   7173.68  189.617
2020-01-01 00:20:00   7173.50   7176.13   7170.69   7171.81  198.838
...                       ...       ...       ...       ...      ...
2023-07-31 23:35:00  29201.20  29207.40  29194.70  29201.50  254.461
2023-07-31 23:40:00  29201.50  29225.30  29199.80  29220.40  405.285
2023-07-31 23:45:00  29220.40  29229.60  29217.00  29229.60  541.594
2023-07-31 23:50:00  29229.50  29229.80  29225.00  29226.00  318.426
2023-07-31 23:55:00  29226.00  29226.10  29219.40  29220.80  256.230

[376704 rows x 5 columns]